nonprofit-dev/force-app/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <label>Coupon</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Coupon</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

nonprofit-dev/force-app/main/default/objects/Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

nonprofit-dev/force-app/main/default/objects/Coupon__c/fields/Coupon_Code__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Code__c</fullName>
    <displayFormat>COUPON-{0000}</displayFormat>
    <label>Coupon Code</label>
    <type>AutoNumber</type>
</CustomField>

nonprofit-dev/force-app/main/default/objects/Reward_Transaction__c/Reward_Transaction__c.object-meta.xml
<CustomObject>
    <label>Reward Transaction</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Reward Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reward Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

nonprofit-dev/force-app/main/default/objects/Reward_Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reward Transactions</relationshipLabel>
    <relationshipName>Reward_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

nonprofit-dev/force-app/main/default/objects/Reward_Transaction__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coupon</label>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Reward Transactions</relationshipLabel>
    <relationshipName>Reward_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

nonprofit-dev/force-app/main/default/objects/Reward_Transaction__c/fields/Coupun_Code__c.field-meta.xml
<CustomField>
    <fullName>Coupun_Code__c</fullName>
    <label>Coupun Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

nonprofit-dev/force-app/main/default/objects/Reward_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Reedemed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

nonprofit-dev/force-app/main/default/classes/CouponTriggerHandler.cls
public class CouponTriggerHandler {

    
    public static void checkAmount(List<Coupon__c> coupons)
    {
        Contact con=[Select id,Name,Balance_Rewards__c from Contact where id=:coupons[0].Contact__c];
       for(Coupon__c cp:coupons)
       {
           if(con.Balance_Rewards__c <cp.Amount__c)
           {
               cp.addError('Not possible');
           }
       }
    }
    public static void createRewardTransaction(List<Coupon__c> coupons)
    {
        Contact con=[Select id,Name,Balance_Rewards__c from Contact where id=:coupons[0].Contact__c];
        
        Reward_Transaction__c rt=new Reward_Transaction__c();
        rt.Status__c='Reedemed';
        rt.Amount__c=coupons[0].Amount__c;
        rt.Contact__c=con.id;
        rt.Coupun_Code__c=coupons[0].Coupon_Code__c;
        rt.Coupon__c=coupons[0].id;
        insert rt;
            
        
       
    }
}